# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vejleder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='navn')),
                ('mail', models.EmailField(max_length=254, verbose_name='email')),
                ('nrBeers', models.IntegerField(default=0, verbose_name='Antal bajere')),
            ],
        ),
    ]
