# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vejleder',
            name='nickName',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kælenavn'),
        ),
    ]
