# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0003_indkoeb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indkoeb',
            old_name='indkoeber',
            new_name='Indkøber',
        ),
    ]
