# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0004_auto_20170412_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='indkoeb',
            name='refunded',
            field=models.BooleanField(default=False, verbose_name='Refunderet'),
        ),
    ]
