# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0006_auto_20170412_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='indkoeb',
            name='nrBeers',
            field=models.IntegerField(default=1337, verbose_name='Antal øl'),
        ),
    ]
