# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0007_indkoeb_nrbeers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrBeers', models.IntegerField(verbose_name='Hvor øl drak personen')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregListe.Indkoeb')),
                ('vejleder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stregListe.Vejleder')),
            ],
        ),
    ]
