# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0008_indtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indkoeb',
            options={'ordering': ['date'], 'verbose_name': 'Indkøb', 'verbose_name_plural': 'Indkøb'},
        ),
        migrations.AlterModelOptions(
            name='indtag',
            options={'ordering': ['event'], 'verbose_name': 'Indtag', 'verbose_name_plural': 'Indtag'},
        ),
        migrations.AlterModelOptions(
            name='vejleder',
            options={'ordering': ['nrBeers'], 'verbose_name': 'Vejleder', 'verbose_name_plural': 'Vejledere'},
        ),
    ]
