# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stregListe', '0009_auto_20170412_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indtag',
            name='nrBeers',
            field=models.IntegerField(verbose_name='Hvor mange øl drak personen'),
        ),
    ]
